version: "3.9"

services:
  sonicplayer:
    image: scjorge/sonicplayer:latest
    container_name: sonicplayer
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      PREPARATION_PATH: /media_preparations
      DATABASE_PATH: /database/sonicplayer.db
      NAVIDROME_MEDIA_PATH: /navidrome_media
      NAVIDROME_DATABASE_SQLITE_PATH: /navidrome_database/navidrome.db
    volumes:
       - ${STORAGE}/sonicplayer/media_preparations:/media_preparations:rw
       - ${APPS}/sonicplayer/database:/database:rw
       - ${STORAGE}/navidrome/music:/navidrome_media:rw
       - ${APPS}/navidrome/data:/navidrome_database:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonicplayer.rule=Host(`sonicplayer.thezion.top`)"
      - "traefik.http.routers.sonicplayer.entrypoints=https"
      - "traefik.http.services.sonicplayer.loadbalancer.server.port=3001"
      - "traefik.http.middlewares.sonicplayer-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.sonicplayer.middlewares=sonicplayer-headers"
